name: Publish Packages

on:
  push:
    tags:
      - "cli-v*"
      - "core-v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}

      - name: Debug tag and tree
        run: |
          echo "Release tag: ${{ github.event.release.tag_name }}"
          pwd
          git rev-parse HEAD
          ls -la
          ls -la package || true
          ls -la packages/cli || true
          ls -la packages/core || true

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Detect component and path
        id: detect
        run: |
          TAG="${{ github.event.release.tag_name }}"
          COMPONENT="${TAG%%-v*}"
          case "$COMPONENT" in
            cli)
              echo "path=packages/cli" >> $GITHUB_OUTPUT
              echo "name=@coffee-machine/cli" >> $GITHUB_OUTPUT
              ;;
            core)
              echo "path=packages/core" >> $GITHUB_OUTPUT
              echo "name=@coffee-machine/core" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "unknown tag: $TAG"
              exit 1
              ;;
          esac

      - name: Build all workspaces
        run: pnpm -r build

      - name: Publish to npm
        working-directory: ${{ steps.detect.outputs.path }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          NAME=$(node -p "require('./package.json').name")
          VER=$(node -p "require('./package.json').version")
          if npm view "$NAME@$VER" version >/dev/null 2>&1; then
            echo "$NAME@$VER already exists on npm. Skipping publish."
            exit 0
          fi
          npm publish --provenance --access public
