name: "release"

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  prepare:
    uses: ./.github/workflows/precheck.yml

  release:
    runs-on: ubuntu-latest
    needs: [prepare]
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: rp
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Checkout
        if: ${{ steps.rp.outputs.releases_created == 'true' }}
        uses: actions/checkout@v4

      - name: Setup pnpm
        if: ${{ steps.rp.outputs.releases_created == 'true' }}
        uses: pnpm/action-setup@v4

      - name: Setup Node
        if: ${{ steps.rp.outputs.releases_created == 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install dependencies
        if: ${{ steps.rp.outputs.releases_created == 'true' }}
        run: pnpm install --frozen-lockfile

      - name: Build
        if: ${{ steps.rp.outputs.releases_created == 'true' }}
        run: pnpm build

      - name: Publish @coffee-machine/cli
        if: ${{ contains(steps.rp.outputs.paths_released, 'package/cli') }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd package/cli
          pnpm -r publish --no-git-checks --access=public

      - name: Publish @coffee-machine/core
        if: ${{ contains(steps.rp.outputs.paths_released, 'package/core') }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd package/core
          pnpm -r publish --no-git-checks --access=public
